### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by anna-citon** [nataliababic/swdevel-lab-hfarm#41]
Push README file, to compose the final README for the project.

**Comment by alepitteri** [comment]
f67b658709d007404aeae8d3b0ed2e5f14b3b0f7

**Comment by rachele2** [comment]
98e7de12e7af7196ea7cf99a9790a5870f05b5d7

**Comment by anna-citon** [comment]
6eb263bb2de957d53efa2387204809947fbb0a47

**Comment by lorenzoparo** [comment]
34c2a65cf4e40707b29d8a6e0af1af2f78e76510

**Comment by nataliababic** [comment]
377f18b337df7aa6b79d8269844bdddcac0c5431

**Comment by rachele2** [comment]
bb68bde43d7bd11740cf11b3ebcef43dc0fa7aa5

**Comment by lorenzoparo** [comment]
e5fcddff511168aa34a89dffde425d1adf953860

**Comment by alepitteri** [comment]
78aefbcfe5291d28b047acae967254cdf3b7d7c8

**Comment by alepitteri** [comment]
78aefbcfe5291d28b047acae967254cdf3b7d7c8
